Meeting/urls.py
from django.urls import path
from . import views
from .views import reports

urlpatterns = [
    path('<int:meeting_id>/checktoken', views.check_token, name='meeting/token_check'),
    path('<int:meeting_id>', views.meeting, name='meeting/detail'),
    path('<int:meeting_id>/new_vote', views.new_vote, name='meeting/new_vote'),
    path('<int:meeting_id>/close', views.close_meeting, name='meeting/close'),
    path('<int:meeting_id>/<int:vote_id>/open_vote', views.open_vote, name='meeting/open_vote'),
    path('<int:meeting_id>/<int:vote_id>/close_vote', views.close_vote, name='meeting/close_vote'),
    path('<int:meeting_id>/<int:vote_id>/close_vote/stv', views.close_vote_stv, name='meeting/close_vote/stv'),
    path('<int:meeting_id>/<int:vote_id>/break_tie', views.break_tie, name='meeting/break_tie'),
    path('manage/<int:meeting_id>', views.manage_meeting, name='meeting/manage'),
    path('manage/<int:meeting_id>/<int:vote_id>', views.manage_vote, name='meeting/manage_vote'),
    path('<int:meeting_id>/announcement', views.announcement, name='meeting/announcement'),
    path('manage/<int:meeting_id>/<int:vote_id>/add_option', views.add_option, name='meeting/add_vote_option'),
    path('manage/<int:meeting_id>/<int:vote_id>/remove_option', views.remove_option, name='meeting/remove_vote_option'),
    path('manage/<int:meeting_id>/create_token', views.create_token, name='meeting/create_token'),
    path('manage/<int:meeting_id>/deactivate_token', views.deactivate_token, name='meeting/deactivate_token'),
    path('reports', reports.report_list, name='meeting/report'),
    path('reports/<int:meeting_id>', reports.meeting_report, name='meeting/report/meeting'),
    path('reports/<int:meeting_id>/<int:vote_id>', reports.vote_report, name='meeting/report/vote'),
    path('list', views.meeting_list, name='meeting/list'),
    path('kiosk_redirect', views.kiosk_redirect, name='meeting/kiosk_redirect')
]

democrapp_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import defaults

urlpatterns = [
    path('print.html?t=<int:token_id>&p=<str:has_proxy>', defaults.permission_denied, name='print_token'),
    path('bulk_tokens.html', defaults.permission_denied, name="bulk_tokens"),
    path('api/admin/', admin.site.urls),
    path('api/',  include('Meeting.urls')),
]

Meeting/models.py
import _thread

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.utils import timezone
from django.db import models
from django.urls import reverse
import uuid
import random

from Meeting.voting_methods import YNA, STV as STVMethod, VoteMethod
from Meeting.tasks import run_count


class Meeting(models.Model):
    time = models.DateTimeField(default=timezone.now)
    name = models.TextField(default='')
    close_time = models.DateTimeField(default=None, null=True, blank=True)

    def open(self):
        return self.close_time is None

    def save(self, *args, **kwargs):
        if self._state.adding:
            super(Meeting, self).save(args, kwargs)
            ts = TokenSet(meeting_id=self.pk)
            ts.save()
        else:
            super(Meeting, self).save(args, kwargs)

    def __str__(self):
        return "{} \t-\t {}".format(self.time.date(), self.name)

    def get_absolute_url(self):
        return reverse('meeting/manage', args=[self.pk])

    def channel_group_name(self):
        return "meeting_{}".format(self.pk)


class TokenSet(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def valid(self):
        return self == self.meeting.tokenset_set.latest('created_at') and self.meeting.open()

    class Meta:
        get_latest_by = 'created_at'


def get_new_token_id():
    x = -1
    while x == -1 or AuthToken.objects.filter(pk=x).exists():
        x = random.randrange(10000000, 99999999)
    return x


class AuthToken(models.Model):
    token_set = models.ForeignKey(TokenSet, on_delete=models.CASCADE)
    has_proxy = models.BooleanField(default=False)
    id = models.PositiveIntegerField(primary_key=True, default=get_new_token_id)
    active = models.BooleanField(default=True)

    def valid_for(self, vote):
        return (vote.token_set == self.token_set) and self.active

    def save(self, *args, **kwargs):
        if self._state.adding:
            super(AuthToken, self).save(args, kwargs)
            vt = VoterToken(auth_token_id=self.pk)
            vt.save()
            if self.has_proxy:
                vt = VoterToken(auth_token_id=self.pk, proxy=True)
                vt.save()
        else:
            super(AuthToken, self).save(args, kwargs)


class Session(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    auth_token = models.ForeignKey(AuthToken, on_delete=models.CASCADE)
    channel = models.TextField(null=True)


class VoterToken(models.Model):
    auth_token = models.ForeignKey(AuthToken, on_delete=models.CASCADE)
    proxy = models.BooleanField(default=False)


class Vote(models.Model):
    token_set = models.ForeignKey(TokenSet, on_delete=models.CASCADE)
    name = models.TextField(default='')
    description = models.TextField(default='')
    results = models.TextField(default='')
    YES_NO_ABS = "YNA"
    STV = "STV"
    methods = (
        (YES_NO_ABS, "Yes No Abs"),
        (STV, "Single Transferable Vote"),
    )
    method_classes = {
        YES_NO_ABS: YNA,
        STV: STVMethod
    }
    method = models.CharField(max_length=3, default=STV, choices=methods)
    READY = 'RE'
    LIVE = 'LI'
    COUNTING = "CO"
    NEEDS_TIE_BREAKER = "TI"
    CLOSED = "CL"
    states = (
        (READY, "Ready"),
        (LIVE, "Live"),
        (COUNTING, "Counting"),
        (NEEDS_TIE_BREAKER, "Needs Tie Breaker"),
        (CLOSED, "Closed"),
    )
    state = models.CharField(max_length=2, default=READY, choices=states)

    def responses(self, exclude_proxies=False):
        if exclude_proxies:
            return BallotEntry.objects.filter(option__vote=self, token__proxy=False).values('token').distinct().count()
        else:
            return BallotEntry.objects.filter(option__vote=self).values('token').distinct().count()

    def save(self, *args, **kwargs):
        if self._state.adding and self.method == self.YES_NO_ABS:
            super(Vote, self).save(*args, **kwargs)
            Option(vote=self, name="yes").save()
            Option(vote=self, name="no").save()
            Option(vote=self, name="abs").save()
        else:
            super(Vote, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def close(self, num_seats):
        self.state = self.COUNTING
        self.save()
        run_count.delay(self.id, num_seats)
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(self.token_set.meeting.channel_group_name(), {"type": "vote.closing",
                                                                                              "vote_id": self.pk})

    def get_method_class(self) -> VoteMethod:
        return self.method_classes[self.method]


class Option(models.Model):
    class Meta:
        unique_together = (('vote', 'name'),)
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='')
    link = models.URLField(null=True)

    def __str__(self):
        return "vote {}: {}".format(self.vote.name, self.name)


class BallotEntry(models.Model):
    class Meta:
        unique_together = (('token', 'option'),
                           #('option__vote', 'value')
                           )

    token = models.ForeignKey(VoterToken, on_delete=models.DO_NOTHING)
    option = models.ForeignKey(Option, on_delete=models.CASCADE)
    value = models.SmallIntegerField(default=1)


class Tie(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    option = models.ForeignKey(Option, on_delete=models.CASCADE)

Meeting/views/announcement.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from ..models import Meeting


@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def announcement(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    if not meeting.open():
        return JsonResponse({"result": "failure",
                             "error": "meeting closed"})
    if "message" not in request.POST:
        return JsonResponse({"result": "failure",
                             "error": "no message"})
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(meeting.channel_group_name(),
                                            {"type": "announcement",
                                             "message": request.POST["message"]})
    return JsonResponse({"result": "success"})

Meeting/views/break_tie.py
from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from ..models import Meeting, Vote, Tie


@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def break_tie(request, meeting_id, vote_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    vote = get_object_or_404(Vote, pk=vote_id)
    if vote.token_set.meeting == meeting and vote.state == vote.READY:
        return JsonResponse({'error': 'meeting vote mismatch'}, status=401)

    if vote.state == Vote.NEEDS_TIE_BREAKER:
        if request.method == "GET":
            options = {}
            for tied_candidate in vote.tie_set.all():
                options[tied_candidate.option.id] = {
                    "name": tied_candidate.option.name
                }
            message = {"type": "tied_options",
                       "options": options,
                       }
            context = {"options": vote.tie_set.all()}
            return render(request, 'meeting/tie_breaking.html', context)
        elif request.method == "POST":
            winner = request.POST['winner_id']
            if not Tie.objects.filter(vote=vote, option_id=winner).exists():
                return JsonResponse({'error': 'winner_id was not an option'}, status=401)

            for tie in Tie.objects.filter(vote=vote).exclude(option_id=winner).all():
                tie.delete()
            vote.state = vote.COUNTING
            vote.save()
            return HttpResponseRedirect(reverse('meeting/manage', args=[meeting_id]))
    else:
        return JsonResponse({"type": "error",
                            "error": "designated stalemate associate un needed"})

Meeting/views/check_token.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from ..models import Meeting, Session

@csrf_exempt
def check_token(request, meeting_id):
    token = request.POST['token']
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    current_set = meeting.tokenset_set.latest('created_at')
    if current_set.authtoken_set.filter(pk=token).exists():
        s = Session(auth_token_id=token)
        s.save()
        sessions = Session.objects.filter(auth_token_id=token)
        response = {
            "success": True,
            "session_token": s.id,
            "num_sessions": sessions.count(),
            "active_sessions": sessions.exclude(channel=None).count(),
        }
        response = JsonResponse(response)
    else:
        response = JsonResponse({"success": False, "reason": "BadToken"})
    response["Access-Control-Allow-Origin"] = "*"
    return response

Meeting/views/close_vote.py
from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from ..models import Meeting, Vote


@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def close_vote(request, meeting_id, vote_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    vote = get_object_or_404(Vote, pk=vote_id)
    if vote.token_set.meeting != meeting or vote.state != vote.LIVE:
        return JsonResponse({'result': 'failure'}, status=401)
    num_seats = int(request.POST['num_seats']) if 'num_seats' in request.POST else 1
    vote.close(num_seats)
    message = {'type': 'success'}
    return HttpResponseRedirect(reverse('meeting/manage', args=[meeting.id]))

@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def close_vote_stv(request, meeting_id, vote_id):
    context = {}
    vote = get_object_or_404(Vote, pk=vote_id)
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    context['vote'] = vote
    context['meeting'] = meeting
    return render(request, 'meeting/close_stv.html', context)

Meeting/views/kiosk_redirect.py
from django.http import HttpResponse
from django.shortcuts import redirect

from Meeting.models import Meeting


def kiosk_redirect(request):
    meeting_query = Meeting.objects.filter(close_time__isnull=True).order_by('-time')
    if meeting_query.exists():
        meeting = meeting_query.first()
        return redirect('/?k=true&m={}'.format(meeting.id))
    else:
        return HttpResponse("No meeting currently running")

Meeting/views/manage_options.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from ..models import Meeting, Vote, Option

@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def add_option(request, meeting_id, vote_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    vote = get_object_or_404(Vote, pk=vote_id)
    if vote.token_set.meeting != meeting or vote.state != Vote.READY or vote.method == Vote.YES_NO_ABS:
        return JsonResponse({"result": "failure"})
    o = Option(name=request.POST['name'], vote=vote)
    o.save()
    return JsonResponse({"result": "success",
                         "id": o.id, })

@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def remove_option(request, meeting_id, vote_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    vote = get_object_or_404(Vote, pk=vote_id)
    if vote.token_set.meeting != meeting or vote.state != Vote.READY or vote.method == Vote.YES_NO_ABS:
        return JsonResponse({"result": "failure"})
    Option.objects.filter(pk=request.POST['id'], vote=vote).delete()
    return JsonResponse({"result": "success"})

Meeting/views/manage_vote.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from ..models import Meeting, Vote


@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def manage_vote(request, meeting_id, vote_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    vote = get_object_or_404(Vote, pk=vote_id)
    if vote.token_set.meeting != meeting:
        return HttpResponse("this vote is not part of the selected meeting")
    if request.method == "POST" and request.POST['_method'] == "DELETE" and vote.state == Vote.READY:
        vote.delete()
        return HttpResponseRedirect(reverse('meeting/manage', args=[meeting.id]))
    context = {'meeting': meeting,
               'vote': vote}
    return render(request, 'meeting/vote.html', context)

Meeting/views/meeting.py
from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from ..models import Meeting


@login_required(login_url='/api/admin/login')
@permission_required('Meeting.add_meeting')
def meeting(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    token_sets = meeting.tokenset_set.order_by('created_at').all()
    votes = []
    for t_set in token_sets:
        votes += t_set.vote_set.all()
    context = {
        'meeting': meeting,
        'token_sets': token_sets,
        'vote_list': votes}
    token_set_dict = {}
    for token_set in token_sets:
        token_set_dict[token_set.id] = token_set.authtoken_set.count()
    vote_dict = {}
    for vote in votes:
        vote_data = {"name": vote.name,
                     "description": vote.description,
                     "method": vote.method,
                     "state": vote.state,
                     }
        vote_dict[vote.id] = vote_data
    message = {
        'name': meeting.name,
        'token_sets': token_set_dict,
        'votes': vote_dict,
    }
    return JsonResponse(message)

Meeting/views/meeting_list.py
from django.http import JsonResponse
from ..models import Meeting


def meeting_list(request):
    meeting_list = []
    for meeting in Meeting.objects.filter(close_time__isnull=True).all():
        meeting_list.append({'id': meeting.id,
                             'name': meeting.name})
    message = {'meetings': meeting_list}
    return JsonResponse(message)

Meeting/templates/meeting/close_stv.html
{% extends 'meeting/_base.html' %}

{% load vote_helpers %}

{% block content %}

<h1>{{ vote.name }}</h1>

<div class="card">
  <h5 class="card-header">How many positions are available?</h5>
  <div class="col-md-6">
          <form action="{% url 'meeting/close_vote' meeting.id vote.id %}" method="post">
                {% csrf_token %}
                <div class="form-group m-1">
                    <input id="num_seats" name="num_seats" type="number">
                    <input type="submit" value="Submit" class="btn btn-primary m-1 align-right" >
                </div>
          </form>
  </div>
</div>

{% endblock %}

Meeting/templates/meeting/meeting.html
{% extends 'meeting/_base.html' %}

{% load vote_helpers %}

{% block content %}

<h1>{{ meeting.name }}</h1>

<div class="card">
  <h5 class="card-header">Manage Ballots</h5>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Action</th>
        <th>Recieved</th>
      </tr>
    </thead>
    {% for vote in votes %}
    <tr>
      <td><a href="{% url 'meeting/manage_vote' meeting.id vote.id%}">{{vote.name}}</a></td>
      <td>{{vote.get_state_display}}</td>
      <td>{% vote_action_button vote %}</td>
      <td>{% vote_responses_or_remove vote csrf_token %}</td>
    </tr>
    {% endfor %}
  </table>
</div>

<div class="card">
  <h5 class="card-header">Create New Ballot</h5>
  <div class="card-body">
    <form action="{% url 'meeting/new_vote' meeting.id %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row">
        <div class="col-md-6">
          <div class="form-group m-1">
            {{ form.name.label_tag }}
            {{ form.name.errors }}
            <input type="text" class="form-control" name="{{ form.name.html_name }}" maxlength="150" required id="{{ form.name.id_for_label }}"></input>
          </div>
          <div class="form-group m-1">
            {{ form.method.label_tag }}
            {{ form.method.errors }}
            <select name="{{ form.method.html_name }}" id="{{ form.method.id_for_label }}" class="form-control">
              <option value="" selected>-- please select --</option>
              {% for x,y in form.method.field.choices %}
                  <option value="{{ x }}">{{ y }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group m-1">
            {{ form.description.label_tag }}
            {{ form.description.errors }}
            <textarea class="form-control col" name="{{ form.description.html_name }}" row="3" maxlength="150" required id="{{ form.description.id_for_label }}"></textarea>
          </div>
          <input type="submit" value="Submit" class="btn btn-sm btn-primary m-1 align-right" />
        </div>
      </div>
    </form>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="card">
        <h5 class="card-header">Create Voter Token</h5>
        <div class="card-body">
          <form>
            {% csrf_token %}
            <div class="row">
              <div class="col">
                <div class="form-check form-check-inline">
                  <label class="form-check-label" for="proxy">voter has proxy?</label>
                  <input class="form-check-input" type="checkbox" id="proxy" name="proxy"/>
                </div>
              </div>
              <div class="col">
                <label for="tokenAmount">Amount of tokens</label>
                <input type="number" class="form-control" name="tokenAmount" min="1" max="100" value="1"/>
              </div>
              <div class="col-auto">
                <input type="button" class="btn btn-sm btn-primary" onclick="create_token()" value="Create Token" />
              </div>
            </div>
          </form>
        </div>
      </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <h5 class="card-header">Send Announcement</h5>
      <div class="card-body">
        <div class="form-group mb-1">
          <textarea class="form-control" id="message_textbox" row="1" required></textarea>
        </div>
        <button type="button" class="btn btn-sm btn-primary" id="announcement_submit" onclick="send_announcement()">Announce</button>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="card">
        <h5 class="card-header">Invalidate voter token</h5>
        <div class="card-body">
          <form id="token_invalidation_form">
            {% csrf_token %}
            <div class="row">
              <div class="col">
                <div class="form-group mb-1">
                  <input type="number" class="form-control" id="invalidate_token_textbox" min="10000000" max="99999999"></input>
                </div>
              </div>
              <div class="col-auto">
                <input type="submit" class="btn btn-sm btn-danger p-1 m-1" onclick="invalidate_token()" value="Invalidate Token"></input>
              </div>
            </div>
          </form>
        </div>
      </div>
  </div>
  <div class="col-md-6">
    <div class="card">
        <h5 class="card-header">Close Meeting</h5>
        <div class="card-body">
          <form action="{% url 'meeting/close' meeting.id %}" method="post">
            {% csrf_token %}
              <input type="submit" class="btn btn-sm btn-danger" onclick="close_meeting(event)" value="Close" />
          </form>
        </div>
      </div>
  </div>
</div>
{% endblock %}

{% block footerscripts %}
<script>
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function send_announcement() {
        var message = $('#message_textbox').val();
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $.ajax({
            type:'POST',
            url: '{% url 'meeting/announcement' meeting.id %}',
            data: {
              'message': message
            },
            dataType: 'json',
            success: function (data) {
              if (data.result == "success") {
                $('#message_textbox').val("")
              }
            },
            error: function(textStatus) {
                alert("Error creating announcement.");
                console.log("Error creating announcement:");
                console.log(textStatus);
            }
        });
    };

    function create_token() {
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
      $.ajax({
        type:'POST',
        url: '{% url 'meeting/create_token' meeting.id %}',
        data: {
          'type': 'create_token',
          'proxy': $('[name=proxy]').prop('checked'),
          'amount': $('[name=tokenAmount]').prop('value'),
        },
        dataType: 'json',
        success: function (data) {
          if (data.result == "success") {
            console.log("Created token.");
            console.log(data);

            // All receipts open as a new tab in the same window.
            window.open(data.print_url, 'receipt_window');
            return;
          }
          else {
            alert("Error creating token. See JS console.");
            console.log("Error creating token:");
            console.log(data);
          }
        },
        error: function(textStatus) {
          alert("Error creating token. See JS console.");
          console.log("Error creating token:");
          console.log(textStatus);
        }
      });
    };
    function invalidate_token() {
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
      $.ajax({
        type:'POST',
        url: '{% url 'meeting/deactivate_token' meeting.id %}',
        data: {
          'key': $('#invalidate_token_textbox')[0].valueAsNumber
        },
        dataType: 'json',
        success: function (data) {
          if (data.result == "success") {
            console.log("invalidated token.");
            console.log(data);
            $('#token_invalidation_form')[0].reset();
            alert("Success");
            return;
          }
          else {
            if (data.reason && data.reason == "token doesnt exist") {
              alert("Token Doesnt exist, check you typed the number in correctly");
            } else {
              alert("Error invalidating token. See JS console.");
              console.log("Error invalidating token:");
              console.log(data);
            }
          }
        },
        error: function(textStatus) {
          alert("Error invalidating token. See JS console.");
          console.log("Error invalidating token:");
          console.log(textStatus);
        }
      });
    };

    function close_meeting(e){
        if(confirm("Are you sure? This will close all open votes and delete unopened ones")){
            return true;
        } else {
            e.preventDefault();
            return false;
        }
    }
</script>
{% endblock %}

Meeting/templates/meeting/vote.html
{% extends 'meeting/_base.html' %}

{% load vote_helpers %}

{% block content %}
    {% csrf_token %}
    <h1>{{ vote.name }}</h1>
    {{ vote.description | linebreaks }}
    --------------------------------
    {{ vote.results | linebreaks }}
    <ul id="option_list">
        {% for option in vote.option_set.all %}
            <li id="{{ option.id }}">{{ option.name }} {% option_remove_button option %}</li>
        {% endfor %}
    </ul>
    {% if vote.method != vote.YES_NO_ABS and vote.state == vote.READY %}
        <input type="text" id="additional_option_textbox">
        <button type="button" class="btn btn-sm btn-primary" id="additional_option_submit" onclick="add_option()">add
        </button>
    {% endif %}
{% endblock %}

{% block footerscripts %}
    <script>
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        function add_option() {
            var new_option = $('#additional_option_textbox').val();
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $.ajax({
                type: 'POST',
                url: '{% url 'meeting/add_vote_option' meeting.id vote.id %}',
                data: {
                    'name': new_option
                },
                dataType: 'json',
                success: function (data) {
                    if (data.result == "success") {
                        $('#option_list').append("<li id='" + data.id + "'>" + new_option + "<button class='btn btn-sm btn-danger' type='button' onclick='remove_option(" + data.id + ")'>remove</button></li>")
                    }
                }
            });
        };

        function remove_option(target) {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $.ajax({
                type: 'POST',
                url: '{% url 'meeting/remove_vote_option' meeting.id vote.id %}',
                data: {
                    'id': target
                },
                dataType: 'json',
                success: function (data) {
                    if (data.result == "success") {
                        $('#' + target).remove()
                    }
                }
            });
        };
    </script>
{% endblock %}